### ISSUE TITLE
Extra blank line with each docs update

### ISSUE THREAD

**Issue by erdaltsksn** [devcontainers/action#128]
It adds an extra blank line at the beginning of the file if there are no changes.

For example: erdaltsksn/devcontainer#9

**Comment by samruddhikhandale** [comment]
Thanks for reporting, looks like a regression in https://github.com/devcontainers/action/pull/127

**Comment by samruddhikhandale** [comment]
@erdaltsksn Can you re-run the docs auto-generate action? This should have been fixed with v1.2.8

Feel free to reopen if the issue resurfaces. Thanks!

**Comment by erdaltsksn** [comment]
> @erdaltsksn Can you re-run the docs auto-generate action? This should have been fixed with v1.2.8
> 
> Feel free to reopen if the issue resurfaces. Thanks!

I removed the extra line and run the action again. It added the blank lines again.
New pull request: erdaltsksn/devcontainer#10
Previous pullreq: erdaltsksn/devcontainer#9

**Comment by erdaltsksn** [comment]
The issue is not solved yet. Can you reopen the issue please? @samruddhikhandale

**Comment by samruddhikhandale** [comment]
Interesting, @erdaltsksn do you mind proving a repro? or sample PRs where you can see this issue. That would be really helpful for debugging the issue, haven't seen this happen for a long time now. Thanks!

**Comment by erdaltsksn** [comment]
> Interesting, @erdaltsksn do you mind proving a repro? or sample PRs where you can see this issue. That would be really helpful for debugging the issue, haven't seen this happen for a long time now. Thanks!

I've tested it with a clean repository and it works well. I guess some other tool messed my docs. Sorry for taking your time.
